### ISSUE TITLE
[FEATURE] Extend supported versions to `2024.3`

### ISSUE THREAD

**Issue by hakimio** [cap-js/cds-intellij#64]
### Description

Jetbrains has released version `2024.3 EAP` of their IDEs but the plugin doesn't support it.

### Suggested Solution

Indicate support for `2024.3`.

**Comment by tim-sh** [comment]
It seems the JetBrains docs are incomplete: I only now learned that an undefined latest IDE version [defaults to](https://plugins.jetbrains.com/docs/intellij/tools-intellij-platform-gradle-plugin-extension.html#intellijPlatform-pluginConfiguration-ideaVersion-untilBuild) `2024.2` in our case, as opposed to ['all the IDEs since'](https://plugins.jetbrains.com/docs/intellij/plugin-configuration-file.html#idea-plugin__idea-version).

**Comment by tim-sh** [comment]
fixed with 1.1.1

**Comment by hakimio** [comment]
Awesome. Thanks 🙂
Let me know once the new version is published.

**Comment by tim-sh** [comment]
@hakimio You're welcome. So, it's out now, please let me know how it behaves.

**Comment by hakimio** [comment]
Thank you, Tim. I can confirm that the updated plugin works great with `2024.3 EAP`.
